#include "graphics/shader/recompiler/CodegenFingerprint.h"

#include "common/rendererBatch.h"
#include "graphics/host_gpu/renderer/cache/bufferCache.h"
#include "graphics/shader/recompiler/CodegenOptions.h"
#include "graphics/shader/recompiler/backend/spirv/SpirvEmitter.h"
#include "kytyCodegenVersion.h"

#include <cstdlib>
#include <cstring>
#include <iterator>
#include <string_view>

namespace Libs::Graphics::ShaderRecompiler {

namespace {

// Generated by src/codegen_version.cmake: every "KYTY_*" string literal of the codegen source set.
constexpr const char* kSwitches[] = {KYTY_CODEGEN_SWITCH_LIST nullptr};
constexpr size_t      kSwitchCount = std::size(kSwitches) - 1;

#if defined(_MSC_VER) && defined(_WIN64) && defined(_ITERATOR_DEBUG_LEVEL) && _ITERATOR_DEBUG_LEVEL == 0
// Members: 28 bools, MadMode, PsLiveExec, loop_guard_budget, loop_guard_shaders, dispatcher_cap,
// rt_node_budget.
// Add a new member to the fingerprint below, then update this size (a new bool can fill padding
// and leave it).
static_assert(sizeof(CodegenOptions) == 80, "CodegenOptions changed: update CodegenFingerprint");
#endif

class Bytes {
public:
	explicit Bytes(std::vector<uint8_t>& out): m_out(out) {}
	void U8(uint8_t value) { m_out.push_back(value); }
	void U32(uint32_t value) { Raw(&value, sizeof(value)); }
	void U64(uint64_t value) { Raw(&value, sizeof(value)); }
	void Text(std::string_view text) {
		U32(static_cast<uint32_t>(text.size()));
		Raw(text.data(), text.size());
	}

private:
	void Raw(const void* data, size_t size) {
		const auto* bytes = static_cast<const uint8_t*>(data);
		m_out.insert(m_out.end(), bytes, bytes + size);
	}
	std::vector<uint8_t>& m_out;
};

} // namespace

std::string_view CodegenVersion() {
	return KYTY_CODEGEN_VERSION;
}

std::span<const char* const> CodegenSwitches() {
	return {kSwitches, kSwitchCount};
}

std::vector<uint8_t> CodegenFingerprint() {
	std::vector<uint8_t> out;
	Bytes                b(out);
	b.Text("KytyCodegenFingerprint/1");
	b.Text(CodegenVersion());

	const auto& options = GetCodegenOptions();
	b.U8(options.movrel_range ? 1u : 0u);
	b.U8(options.fast_float_min_max ? 1u : 0u);
	b.U8(options.fast_pkrtz ? 1u : 0u);
	b.U8(options.single_f2i_saturation ? 1u : 0u);
	b.U8(options.lod_stats_gate ? 1u : 0u);
	b.U8(options.robust_buffer_loads ? 1u : 0u);
	b.U32(static_cast<uint32_t>(options.mad_mode));
	b.U8(options.interp_modes ? 1u : 0u);
	b.U8(options.sample_offsets ? 1u : 0u);
	b.U8(options.sample_lod_clamp ? 1u : 0u);
	b.U8(options.host_ftz_inputs ? 1u : 0u);
	b.U8(options.exec_selects ? 1u : 0u);
	b.U8(options.ps_append_live_election ? 1u : 0u);
	b.U32(static_cast<uint32_t>(options.ps_live_exec));
	b.U32(options.loop_guard_budget);
	b.U32(static_cast<uint32_t>(options.loop_guard_shaders.size()));
	for (const auto hash: options.loop_guard_shaders) {
		b.U64(hash);
	}
	b.U8(options.srt_variant_reads ? 1u : 0u);
	b.U8(options.mesh_indirect_params ? 1u : 0u);
	b.U8(options.movrel_known_zeros ? 1u : 0u);
	b.U8(options.movrel_switch ? 1u : 0u);
	b.U8(options.uniform_lane_reads ? 1u : 0u);
	b.U8(options.short_f32_helpers ? 1u : 0u);
	b.U8(options.realtime_clock ? 1u : 0u);
	b.U8(options.dpp_skip_inactive ? 1u : 0u);
	b.U8(options.lane_reductions ? 1u : 0u);
	b.U32(options.dispatcher_cap);
	b.U8(options.ir_linear_uses ? 1u : 0u);
	b.U8(options.fold_lane_masks ? 1u : 0u);
	b.U8(options.rt_stub ? 1u : 0u);
	b.U8(options.rt_software ? 1u : 0u);
	b.U8(options.rt_type6 ? 1u : 0u);
	b.U8(options.bda_writes ? 1u : 0u);
	b.U32(options.rt_node_budget);
	b.U8(options.rt_node_stats ? 1u : 0u);

	// Host device state the emitter reads (set once by the device layer).
	const auto float_controls = Spirv::GetHostFloatControls();
	b.U8(float_controls.denorm_flush_f32 ? 1u : 0u);
	b.U8(float_controls.denorm_preserve_f16 ? 1u : 0u);
	b.U8(float_controls.denorm_preserve_f64 ? 1u : 0u);
	b.U8(Spirv::GetHostBufferRobustness().storage_dword_loads_return_zero ? 1u : 0u);
	const auto image_features = Spirv::GetHostImageFeatures();
	b.U8(image_features.min_lod ? 1u : 0u);
	b.U8(static_cast<uint8_t>(image_features.compute_derivatives));
	const auto shader_clock = Spirv::GetHostShaderClock();
	b.U8(static_cast<uint8_t>(shader_clock.scope));
	b.U32(static_cast<uint32_t>(shader_clock.shift));

	// Outside the source set: ExtractResourcePlan's flow aliases, and the page constants the
	// BDA page-table walk bakes into SPIR-V (spirvEmitterMemory.cpp).
	b.U8(Common::RendererBatchEnabled() ? 1u : 0u);
	b.U64(BufferCache::CACHING_PAGEBITS);
	b.U64(BufferCache::CACHING_PAGESIZE);

	b.U32(static_cast<uint32_t>(kSwitchCount));
	for (size_t i = 0; i < kSwitchCount; ++i) {
		b.Text(kSwitches[i]);
		const auto* value = std::getenv(kSwitches[i]);
		b.U8(value != nullptr ? 1u : 0u);
		b.Text(value != nullptr ? std::string_view(value) : std::string_view());
	}
	return out;
}

} // namespace Libs::Graphics::ShaderRecompiler
